/**
 * agent-events.ts — closed discriminated union for SSE events emitted
 * by the M13 agent runtime over the per-user streaming channel.
 *
 * Spec ref:
 *   openspec/changes/add-agent-runtime-streaming/specs/streaming-channel/spec.md
 *     "SSE event types are a closed discriminated union"
 *
 * The schema is the contract between the server (apps/api/src/agent/
 * streaming.ts) and any future client consumer (M14 Side Panel). The
 * runId on every event is a UUID v4 generated by the run endpoint
 * (apps/api/src/agent/sse-endpoint.ts) — see streaming-channel spec
 * "Run id format".
 */

import { z } from "zod";

const uuidV4 = z
  .string()
  .regex(
    /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i,
    "runId must be a UUID v4",
  );

/**
 * Closed list of i18n error keys the runtime is allowed to emit on an
 * `error` event or carry inside a `tool_result.result.errorKey`. Adding
 * a new error path requires:
 *   1. Add the key here.
 *   2. Add the translation to packages/shared/locales/zh-TW.json and
 *      packages/shared/locales/en.json under the `agent.error.*` group.
 */
export const agentErrorKeys = [
  "agent.error.byokMissing",
  "agent.error.providerAuth",
  "agent.error.providerRateLimit",
  "agent.error.providerServer",
  "agent.error.wallTimeout",
  "agent.error.toolCallCap",
  "agent.error.permissionDenied",
  "agent.error.cancelled",
  "agent.error.internal",
  "agent.error.invalidRequest",
  "agent.error.runIdReused",
  "agent.error.rateLimited",
] as const;

export type AgentErrorKey = (typeof agentErrorKeys)[number];

const agentErrorKeySchema = z.enum(agentErrorKeys);

const textEventSchema = z
  .object({
    type: z.literal("text"),
    runId: uuidV4,
    delta: z.string(),
  })
  .strict();

const toolCallEventSchema = z
  .object({
    type: z.literal("tool_call"),
    runId: uuidV4,
    callId: z.string().min(1),
    name: z.string().min(1),
    args: z.record(z.string(), z.unknown()),
  })
  .strict();

/**
 * tool_result.result is either an opaque success payload (shape
 * depends on the tool — registry decides) or an error envelope. We
 * accept both via z.union so the schema is stable when new tools land.
 */
const toolResultPayloadSchema = z.union([
  z.object({ errorKey: z.string().min(1) }).strict(),
  z.record(z.string(), z.unknown()),
]);

const toolResultEventSchema = z
  .object({
    type: z.literal("tool_result"),
    runId: uuidV4,
    callId: z.string().min(1),
    result: toolResultPayloadSchema,
  })
  .strict();

const errorEventSchema = z
  .object({
    type: z.literal("error"),
    runId: uuidV4,
    errorKey: agentErrorKeySchema,
    detail: z.string().optional(),
  })
  .strict();

/**
 * Per-run aggregated token totals from the provider, summed across every
 * turn of the multi-turn tool loop. `usage: null` is allowed only when
 * the provider's response did not include usage information (rare).
 *
 * The `provider` literal mirrors the BYOK provider enum elsewhere in the
 * codebase (apps/api/src/byok/providers/*); adding a fourth provider
 * requires extending this list AND the title-gen economy table AND the
 * BYOK pricing table.
 */
const usageSchema = z
  .object({
    input: z.number().int().nonnegative(),
    output: z.number().int().nonnegative(),
    provider: z.enum(["openai", "anthropic", "google"]),
    model: z.string().min(1),
  })
  .strict();

const doneEventSchema = z
  .object({
    type: z.literal("done"),
    runId: uuidV4,
    usage: usageSchema.nullable(),
  })
  .strict();

export const agentEventSchema = z.discriminatedUnion("type", [
  textEventSchema,
  toolCallEventSchema,
  toolResultEventSchema,
  errorEventSchema,
  doneEventSchema,
]);

export type AgentEvent = z.infer<typeof agentEventSchema>;
export type AgentTextEvent = z.infer<typeof textEventSchema>;
export type AgentToolCallEvent = z.infer<typeof toolCallEventSchema>;
export type AgentToolResultEvent = z.infer<typeof toolResultEventSchema>;
export type AgentErrorEvent = z.infer<typeof errorEventSchema>;
export type AgentDoneEvent = z.infer<typeof doneEventSchema>;
export type AgentRunUsage = z.infer<typeof usageSchema>;
